<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWdbT4G9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWdbT4G9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWdbT4G9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWdbT4G9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWdbT4G9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WdbT4G9',
    'container.build_id' => 'fa5f6afe',
    'container.build_time' => 1564126790,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWdbT4G9');
